export interface CuratedAlternative {
  name: string;
  manaValue: number;
  typeLine: string;
  priceUsd: number;
  oracleText: string;
  imageUri?: string;
  similarityScore: number;
  role: 'best_overall' | 'cheapest' | 'closest_functional' | 'alternative';
  whySimilar: string;
  whatItDoesDifferently: string;
  advantages: string[];
  disadvantages: string[];
  idealDeckSituation: string;
  sharedTags?: string[];
}

export interface CuratedCardGuide {
  cardName: string;
  cleanSlug: string;
  marketPrice: number;
  manaValue: number;
  colorIdentity: string[];
  typeLine: string;
  oracleText: string;
  imageUri: string;
  cardRole: string;
  summaryProblem: string;
  whyExpensive: string;
  bestOverallReason: string;
  cheapestReason: string;
  closestFunctionalReason: string;
  whenNotToSwap: string;
  archetypeGuidance: {
    archetype: string;
    recommendedCard: string;
    rationale: string;
  }[];
  customFaqs: {
    question: string;
    answer: string;
  }[];
  alternatives: CuratedAlternative[];
  relatedHubSlug: string;
  relatedCategoryName: string;
}

export const CURATED_CARD_GUIDES: Record<string, CuratedCardGuide> = {
  'badgermole-cub': {
    cardName: 'Badgermole Cub',
    cleanSlug: 'badgermole-cub',
    marketPrice: 18.50,
    manaValue: 2,
    colorIdentity: ['G'],
    typeLine: 'Creature — Badger Mole',
    oracleText: 'Earthbending — Whenever Badgermole Cub attacks, you may tap an untapped creature you control. If you do, untap target land.\nWhenever you tap a creature to pay a cost or activate an ability, put a +1/+1 counter on Badgermole Cub.',
    imageUri: 'https://cards.scryfall.io/normal/front/6/8/68f7b764-500b-4654-8e5a-27768e8e6f0b.jpg',
    cardRole: 'Land Untap Engine & Creature-Tap Synergies',
    summaryProblem: 'Looking for a Badgermole Cub replacement or budget alternatives without paying $18+? Badgermole Cub is a breakout green creature providing repeatable land untapping during combat (Earthbending) and +1/+1 counter scaling whenever your creatures tap for abilities. For budget Commander decks and green ramp lists, several powerful substitutes replicate its land-untapping engine and mana acceleration for under $1.50.',
    whyExpensive: 'High demand across Commander and casual constructed formats due to explosive untap combos with Nykthos, Gaea\'s Cradle, and multi-mana lands, combined with organic creature-tapping scaling.',
    bestOverallReason: 'Quirion Ranger ($1.20) and Wirewood Symbiote ($0.80) deliver instant-speed, zero-mana repeatable creature and land resets every turn cycle without being restricted to combat.',
    cheapestReason: 'Hope Tender ($0.25) and Arbor Elf ($0.35) cost under $0.50 and provide dedicated, repeatable land untapping on cheap green creature bodies.',
    closestFunctionalReason: 'Hope Tender directly untaps ANY target land (including nonbasic utility lands like Nykthos and Lotus Field) on a 2-CMC green body, with the ability to exert and untap two lands at once.',
    whenNotToSwap: 'If your deck specifically relies on the free Earthbending attack trigger to untap massive mana lands without paying mana activation costs or bouncing Forests, Badgermole Cub offers a unique combat line.',
    archetypeGuidance: [
      { archetype: 'Elfball / Green Creature Swarm', recommendedCard: 'Wirewood Symbiote', rationale: 'Bounces 1-drop elves to protect them from spot removal while untapping mana dorks like Priest of Titania or Elvish Archdruid.' },
      { archetype: 'Land Enchantment / Enchantress', recommendedCard: 'Arbor Elf', rationale: 'Pairs with Wild Growth, Utopia Sprawl, and Fertile Ground to produce 4–6 mana as early as turn 3.' },
      { archetype: 'Big Mana / Utility Land Decks', recommendedCard: 'Hope Tender', rationale: 'Untaps any nonbasic land (Nykthos, Lotus Field, Cabal Coffers) with a single activation, saving 98% over Badgermole Cub.' },
      { archetype: 'Midrange & Untap Combos', recommendedCard: 'Quirion Ranger', rationale: 'Guarantees land drops on turn cycles and untaps high-impact utility creatures during opponent turns at instant speed.' },
    ],
    customFaqs: [
      { question: 'What is the best Badgermole Cub replacement in MTG Commander?', answer: 'Quirion Ranger ($1.20) is the best overall replacement for Badgermole Cub. It costs only 1 green mana ({G}), operates at instant speed on any player\'s turn, and resets high-value mana dorks or utility creatures without needing to attack in combat.' },
      { question: 'What is the cheapest replacement for Badgermole Cub?', answer: 'Hope Tender ($0.25) and Arbor Elf ($0.35) are the most affordable replacements. Both cost under $0.50, saving deckbuilders over 98% compared to Badgermole Cub ($18.50).' },
      { question: 'What cards are like Badgermole Cub for untapping lands?', answer: 'Cards like Hope Tender, Arbor Elf, Kiora\'s Follower, Earthcraft, and Magus of the Candelabra share Badgermole Cub\'s ability to untap lands and generate explosive mana acceleration.' },
      { question: 'Can Hope Tender untap nonbasic lands like Badgermole Cub?', answer: 'Yes! Unlike Arbor Elf (which only targets Forests), Hope Tender can untap ANY land, including high-yield nonbasics like Nykthos, Shrine to Nyx, Lotus Field, Cabal Coffers, and bounce lands.' },
      { question: 'Why is Badgermole Cub so expensive ($18+)?', answer: 'Badgermole Cub surged to $18+ due to its unique combination of Earthbending (combat land untapping) and continuous counter growth whenever creatures tap for mana or abilities, creating explosive synergy in green Commander lists.' },
    ],
    alternatives: [
      {
        name: 'Quirion Ranger',
        manaValue: 1,
        typeLine: 'Creature — Elf',
        priceUsd: 1.20,
        oracleText: 'Return a Forest you control to its owner\'s hand: Untap target creature. Activate only once each turn.',
        imageUri: 'https://cards.scryfall.io/normal/front/3/2/320f1a43-8896-4609-b74e-5e363eac2b98.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: '1-mana green creature that untaps permanents repeatedly each turn cycle without requiring mana payment.',
        whatItDoesDifferently: 'Returns a Forest to hand to untap a creature at instant speed, rather than tapping a creature in combat to untap a land.',
        advantages: ['Costs only 1 mana ({G})', 'Instant-speed activation on opponent turns', 'Guarantees land drops when mana screwed'],
        disadvantages: ['Bounces a Forest to hand', 'Does not grow with +1/+1 counters'],
        idealDeckSituation: 'Green creature-heavy decks with powerful tap abilities like Elvish Archdruid or Circle of Dreams Druid.',
      },
      {
        name: 'Arbor Elf',
        manaValue: 1,
        typeLine: 'Creature — Elf Druid',
        priceUsd: 0.35,
        oracleText: '{T}: Untap target Forest.',
        imageUri: 'https://cards.scryfall.io/normal/front/4/b/4b81165e-f091-4211-8b47-5ea6868b0d4c.jpg',
        similarityScore: 88,
        role: 'cheapest',
        whySimilar: 'Provides direct land untapping on a cheap green creature body.',
        whatItDoesDifferently: 'Directly taps itself to untap a Forest instead of triggering on attacks or creature taps.',
        advantages: ['Costs only 1 mana ({G})', 'Extremely cheap ($0.35)', 'Insane synergy with land auras like Wild Growth'],
        disadvantages: ['Can only target lands with the Forest subtype', 'Does not scale in combat'],
        idealDeckSituation: 'Enchantress or ramp decks running Utopia Sprawl, Fertile Ground, or shocklands.',
      },
      {
        name: 'Hope Tender',
        manaValue: 2,
        typeLine: 'Creature — Human Druid',
        priceUsd: 0.25,
        oracleText: '{1}, {T}: Untap target land.\nExert Hope Tender as it activates this ability: Untap two target lands.',
        imageUri: 'https://cards.scryfall.io/normal/front/9/a/9a66b742-7792-4966-958e-3442d8297b33.jpg',
        similarityScore: 90,
        role: 'closest_functional',
        whySimilar: '2-CMC green creature dedicated directly to untapping any target lands.',
        whatItDoesDifferently: 'Uses an exert mechanic and 1-mana activation rather than combat earthbending.',
        advantages: ['Can untap ANY land (including Nykthos, Cabal Coffers, Lotus Field)', 'Can exert to untap two lands at once'],
        disadvantages: ['Requires 1 mana to activate', 'Exert prevents untapping during your next upkeep'],
        idealDeckSituation: 'Big-mana decks running bounce lands, Lotus Field, or high-value utility lands.',
      },
      {
        name: 'Kiora\'s Follower',
        manaValue: 2,
        typeLine: 'Creature — Merfolk Wizard',
        priceUsd: 0.45,
        oracleText: '{T}: Untap another target permanent.',
        imageUri: 'https://cards.scryfall.io/normal/front/d/9/d9704f4f-eb5b-4862-8efd-ff1d8fd4177a.jpg',
        similarityScore: 89,
        role: 'alternative',
        whySimilar: '2-CMC creature that taps to untap lands and permanents.',
        whatItDoesDifferently: 'Requires Simic ({G}{U}) color identity, but can untap ANY permanent (artifacts, creatures, lands).',
        advantages: ['Can untap creatures, artifacts, planeswalkers, and lands', 'Zero mana activation cost'],
        disadvantages: ['Requires Blue mana in color identity'],
        idealDeckSituation: 'Simic or multi-color decks with activated abilities, mana rocks, or powerful commanders.',
      },
      {
        name: 'Wirewood Symbiote',
        manaValue: 1,
        typeLine: 'Creature — Insect',
        priceUsd: 0.80,
        oracleText: 'Return an Elf you control to its owner\'s hand: Untap target creature. Activate only once each turn.',
        imageUri: 'https://cards.scryfall.io/normal/front/8/5/854f1d22-f4ab-4ce0-8c77-b323d44b3621.jpg',
        similarityScore: 85,
        role: 'alternative',
        whySimilar: '1-mana green engine providing free creature untaps and protection every turn cycle.',
        whatItDoesDifferently: 'Bounces an Elf to protect it from board wipes and re-trigger ETB effects.',
        advantages: ['Instant-speed board wipe protection for your best creatures', 'Costs only 1 mana'],
        disadvantages: ['Requires Elf tribal support'],
        idealDeckSituation: 'Elfball, Tyvar, or green creature combo decks.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Ramp & Mana Acceleration',
  },

  'rhystic-study': {
    cardName: 'Rhystic Study',
    cleanSlug: 'rhystic-study',
    marketPrice: 42.00,
    manaValue: 3,
    colorIdentity: ['U'],
    typeLine: 'Enchantment',
    oracleText: 'Whenever an opponent casts a spell, you may draw a card unless that player pays {1}.',
    imageUri: 'https://cards.scryfall.io/normal/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg',
    cardRole: 'Continuous Spell-Cast Tax & Card Advantage Engine',
    summaryProblem: 'Rhystic Study is Commander’s most infamous passive card advantage engine. Forcing 3 opponents to pay {1} for every spell or draw you dozens of cards has driven its price past $40+. Budget blue deck builders need reliable taxation and draw engines without the hefty investment.',
    whyExpensive: 'Ubiquitous staple in virtually 100% of blue Commander decks due to multiplayer tax scaling and zero upkeep cost.',
    bestOverallReason: 'Mystic Remora costs only 1 mana and taxes noncreature spells for {4}, drawing massive bursts of cards against fast mana and ramp.',
    cheapestReason: 'Unifying Theory costs under $0.50 and imposes a {2} cast tax to draw, delivering 95% functional mechanics.',
    closestFunctionalReason: 'Verity Circle & Soul Barrier tax opponent game actions directly for card advantage and damage.',
    whenNotToSwap: 'In high-power/cEDH tables where opponents cast dozens of low-cost spells per turn cycle, Rhystic Study’s universal {1} tax has no true substitute.',
    archetypeGuidance: [
      { archetype: 'Competitive / High Power', recommendedCard: 'Mystic Remora', rationale: 'Taxes turn 1–3 Sol Rings, Signets, and Tutors for {4}—drawing 4+ cards for 1 mana.' },
      { archetype: 'Casual Multiplayer / Group Hug', recommendedCard: 'Unifying Theory', rationale: 'Applies a {2} tax to draw cards, generating high political engagement.' },
      { archetype: 'Tap / Control', recommendedCard: 'Verity Circle', rationale: 'Draws cards whenever opponent creatures tap without attacking (dorks, utility).' },
    ],
    customFaqs: [
      { question: 'What is the best budget alternative to Rhystic Study?', answer: 'Mystic Remora ($6.00) is the undisputed best overall alternative. It costs only {U} to cast and taxes opponents {4} for every noncreature spell, regularly drawing 4–7 cards in early turns.' },
      { question: 'What is the cheapest replacement for Rhystic Study?', answer: 'Unifying Theory ($0.44) and Soul Barrier ($0.25) are the cheapest direct replacements, providing spell-cast taxation for under $0.50.' },
      { question: 'Why is Rhystic Study so expensive in Commander?', answer: 'Rhystic Study triggers on ALL opponent spells with no upkeep cost. In a 4-player pod, it routinely generates 15+ cards or slows opponents by 10+ mana per game.' },
      { question: 'Is Mystic Remora better than Rhystic Study?', answer: 'In fast or high-power games, Mystic Remora is often BETTER than Rhystic Study because it costs only 1 mana and taxes {4} instead of {1}. In long, casual games, Rhystic Study wins due to having no cumulative upkeep.' },
    ],
    alternatives: [
      {
        name: 'Mystic Remora',
        manaValue: 1,
        typeLine: 'Enchantment',
        priceUsd: 6.00,
        oracleText: 'Cumulative upkeep {1}\nWhenever an opponent casts a noncreature spell, you may draw a card unless that player pays {4}.',
        imageUri: 'https://cards.scryfall.io/normal/front/1/3/13a08c07-e8b8-43bf-99e6-d268c79a62bf.jpg',
        similarityScore: 96,
        role: 'best_overall',
        whySimilar: 'Blue enchantment that taxes opponent spell casts with massive card draw.',
        whatItDoesDifferently: 'Only triggers on noncreature spells, taxes {4} instead of {1}, and has cumulative upkeep.',
        advantages: ['Costs only 1 mana ({U})', 'Taxes {4} (virtually impossible to pay early)', 'Draws enormous bursts of cards on turns 1–4'],
        disadvantages: ['Has cumulative upkeep {1}', 'Does not trigger on creature spells'],
        idealDeckSituation: 'Any blue deck looking for explosive early-game card advantage.',
      },
      {
        name: 'Unifying Theory',
        manaValue: 2,
        typeLine: 'Enchantment',
        priceUsd: 0.44,
        oracleText: 'Whenever a player casts a spell, that player may pay {2}. If the player does, they draw a card.',
        imageUri: 'https://cards.scryfall.io/normal/front/8/e/8e3a2417-cb38-4228-a4aa-1d6fc2c4c8d5.jpg',
        similarityScore: 90,
        role: 'cheapest',
        whySimilar: '2-CMC blue enchantment creating spell-cast tax and card draw triggers.',
        whatItDoesDifferently: 'Symmetrical: allows opponents to pay {2} to draw as well.',
        advantages: ['Costs under $0.50 (99% savings)', 'Low 2-CMC curve'],
        disadvantages: ['Can give opponents card advantage if they have spare mana'],
        idealDeckSituation: 'Casual EDH and group hug decks with high mana constraints.',
      },
      {
        name: 'Verity Circle',
        manaValue: 3,
        typeLine: 'Enchantment',
        priceUsd: 0.55,
        oracleText: 'Whenever an opponent\'s creature becomes tapped, if it wasn\'t declared as an attacker, you may draw a card.\n{4}{U}: Tap target creature without flying.',
        imageUri: 'https://cards.scryfall.io/normal/front/3/d/3d866d26-b630-46d3-be67-4a57234e907b.jpg',
        similarityScore: 86,
        role: 'closest_functional',
        whySimilar: '3-CMC blue enchantment providing passive, repeatable card draw whenever opponents use their permanents.',
        whatItDoesDifferently: 'Triggers on creature taps (mana dorks, abilities) rather than spell casts.',
        advantages: ['Completely shuts down green mana dorks and tap commanders', 'Includes a built-in mana sink tap ability'],
        disadvantages: ['Relies on opponents tapping creatures outside combat'],
        idealDeckSituation: 'Blue control decks facing heavy creature-utility or mana-dork metas.',
      },
    ],
    relatedHubSlug: 'card-draw',
    relatedCategoryName: 'Card Draw Engines',
  },

  'esper-sentinel': {
    cardName: 'Esper Sentinel',
    cleanSlug: 'esper-sentinel',
    marketPrice: 34.00,
    manaValue: 1,
    colorIdentity: ['W'],
    typeLine: 'Artifact Creature — Human Soldier',
    oracleText: 'Whenever an opponent casts their first noncreature spell each turn, draw a card unless that player pays {X}, where X is Esper Sentinel\'s power.',
    imageUri: 'https://cards.scryfall.io/normal/front/f/3/f3537373-0452-466d-ab60-93f4931a067a.jpg',
    cardRole: 'Turn-One Noncreature Draw Tax Engine',
    summaryProblem: 'Esper Sentinel is White’s premier 1-drop card draw staple. Taxing opponents for casting artifacts, enchantments, and spells on curve has made it a $34 must-have. Budget White deck builders need consistent card advantage without paying modern-staple prices.',
    whyExpensive: 'Unmatched 1-mana efficiency in White that scales with equipment and +1/+1 counters.',
    bestOverallReason: 'Loran of the Third Path combines Disenchant removal with repeatable multiplayer card draw on a creature body.',
    cheapestReason: 'Secret Rendezvous ($0.25) and Cut a Deal ($0.30) draw 3 cards immediately for under 3 mana.',
    closestFunctionalReason: 'Archivist of Oghma & Deep Gnome Terramancer trigger passively on opponent tutors and land ramp.',
    whenNotToSwap: 'If your deck relies heavily on Equipment/Anthems to boost Sentinel’s power to {3}+ for an unbreakable tax.',
    archetypeGuidance: [
      { archetype: 'White Weenie / Equipment', recommendedCard: 'Archivist of Oghma', rationale: 'Flash 2-drop that draws cards and gains life whenever opponents search their libraries.' },
      { archetype: 'Control / Midrange', recommendedCard: 'Loran of the Third Path', rationale: 'Destroys a Sol Ring or Rhystic Study upon entry, then taps to draw.' },
      { archetype: 'Tokens / Go-Wide', recommendedCard: 'Welcoming Vampire', rationale: 'Guaranteed 1 card per turn whenever 2-or-less power creatures enter.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Esper Sentinel?', answer: 'Archivist of Oghma ($4.50) and Welcoming Vampire ($1.25) are the strongest alternatives, providing passive turn-over-turn card advantage.' },
      { question: 'What is the cheapest replacement for Esper Sentinel?', answer: 'Cut a Deal ($0.30) and Secret Rendezvous ($0.25) draw 3 cards for under $0.50.' },
      { question: 'Why is Esper Sentinel so good?', answer: 'Because it lands on turn 1, taxes every opponent\'s ramp/sol rings, and scales if you equip it with power-boosting gear.' },
    ],
    alternatives: [
      {
        name: 'Archivist of Oghma',
        manaValue: 2,
        typeLine: 'Creature — Halfling Cleric',
        priceUsd: 4.50,
        oracleText: 'Flash\nWhenever an opponent searches their library, you gain 1 life and draw a card.',
        imageUri: 'https://cards.scryfall.io/normal/front/f/6/f6589e02-8c84-4069-88d1-ebcc8520cae1.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: 'Cheap White creature providing passive card draw off opponent actions.',
        whatItDoesDifferently: 'Has Flash and triggers on opponent tutors and fetch lands rather than noncreature casts.',
        advantages: ['Flash allows surprise deployment', 'Opponents cannot pay mana to prevent the draw', 'Gains life'],
        disadvantages: ['Costs 2 mana ({1}{W}) instead of 1'],
        idealDeckSituation: 'Multiplayer Commander games where fetch lands, ramp spells, and tutors are frequent.',
      },
      {
        name: 'Welcoming Vampire',
        manaValue: 3,
        typeLine: 'Creature — Vampire',
        priceUsd: 1.25,
        oracleText: 'Flying\nWhenever one or more other creatures with power 2 or less enter the battlefield under your control, draw a card. This ability triggers only once each turn.',
        imageUri: 'https://cards.scryfall.io/normal/front/2/d/2d3f6b83-163f-425b-8664-797bcbed7c77.jpg',
        similarityScore: 87,
        role: 'cheapest',
        whySimilar: 'White creature generating steady card advantage.',
        whatItDoesDifferently: 'Triggers on your own small creatures entering rather than taxing opponents.',
        advantages: ['Guaranteed draw under your control', 'Evasive 2/3 flying body'],
        disadvantages: ['Costs 3 mana ({2}{W})', 'Limited to 1 draw per turn'],
        idealDeckSituation: 'Token, Aristocrats, or small creature aggro decks.',
      },
    ],
    relatedHubSlug: 'card-draw',
    relatedCategoryName: 'White Card Advantage',
  },

  'phyrexian-altar': {
    cardName: 'Phyrexian Altar',
    cleanSlug: 'phyrexian-altar',
    marketPrice: 28.00,
    manaValue: 3,
    colorIdentity: [],
    typeLine: 'Artifact',
    oracleText: 'Sacrifice a creature: Add one mana of any color.',
    imageUri: 'https://cards.scryfall.io/normal/front/d/5/d56d9e00-f95e-4045-a745-f09c73e13460.jpg',
    cardRole: 'Free Color-Fixing Sacrifice Outlet & Combo Engine',
    summaryProblem: 'Phyrexian Altar is the premier colored-mana sacrifice outlet in MTG, enabling infinite loops with Gravecrawler, Reassembling Skeleton, and token generators. At $28+, budget Aristocrats players need reliable, free sacrifice outlets.',
    whyExpensive: 'Infinite combo staple with 100+ cards due to producing colored mana at instant speed with zero activation cost.',
    bestOverallReason: 'Ashnod\'s Altar produces 2 colorless mana per sacrifice, providing even higher raw mana velocity for artifact and generic costs.',
    cheapestReason: 'Spawning Pit ($0.40) and Viscera Seer ($0.35) offer instant-speed, zero-mana sacrifice outlets under $0.50.',
    closestFunctionalReason: 'Warren Soultrader & Thermopod produce colored mana directly from creature sacrifices.',
    whenNotToSwap: 'When your combo strictly requires COLORED mana to re-cast a 1-mana creature like Gravecrawler without an auxiliary converter.',
    archetypeGuidance: [
      { archetype: 'Aristocrats / Graveyard', recommendedCard: 'Ashnod\'s Altar', rationale: 'Sacrificing creatures for {2} mana accelerates big spells and death triggers effortlessly.' },
      { archetype: 'Black Life-Drain Combo', recommendedCard: 'Warren Soultrader', rationale: 'Sacrifices creatures and pays 1 life to create Treasure tokens (colored mana).' },
      { archetype: 'Token Swarm', recommendedCard: 'Spawning Pit', rationale: 'Zero-mana sac outlet that rebuilds your board with 2/2 Spawn tokens after a wipe.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Phyrexian Altar?', answer: 'Ashnod\'s Altar ($7.00) is the best alternative, generating {2} generic mana per creature instead of one colored mana.' },
      { question: 'What is the cheapest free sacrifice outlet in MTG?', answer: 'Viscera Seer ($0.35), Carrion Feeder ($0.40), and Spawning Pit ($0.45) all sacrifice creatures for free with zero mana cost.' },
      { question: 'Does Ashnod\'s Altar go infinite like Phyrexian Altar?', answer: 'Yes! While Ashnod\'s produces colorless mana, it forms infinite loops with cards like Nim Deathmantle, Eldrazi Scions, and token generators.' },
    ],
    alternatives: [
      {
        name: 'Ashnod\'s Altar',
        manaValue: 3,
        typeLine: 'Artifact',
        priceUsd: 7.00,
        oracleText: 'Sacrifice a creature: Add {C}{C}.',
        imageUri: 'https://cards.scryfall.io/normal/front/3/c/3c0f7f57-3a17-4db4-b49b-381c81525992.jpg',
        similarityScore: 95,
        role: 'best_overall',
        whySimilar: '3-CMC colorless artifact that sacrifices creatures for mana at instant speed.',
        whatItDoesDifferently: 'Produces {2} generic mana instead of 1 colored mana.',
        advantages: ['Generates DOUBLE the mana output per creature (2 mana vs 1)', 'Extremely resilient combo enabler'],
        disadvantages: ['Mana is colorless, requiring fixing for colored recast costs'],
        idealDeckSituation: 'Aristocrats, Token, and combo decks needing large mana spikes.',
      },
      {
        name: 'Spawning Pit',
        manaValue: 2,
        typeLine: 'Artifact',
        priceUsd: 0.40,
        oracleText: 'Sacrifice a creature: Put a charge counter on Spawning Pit.\n{1}, Remove two charge counters from Spawning Pit: Create a 2/2 colorless Spawn artifact creature token.',
        imageUri: 'https://cards.scryfall.io/normal/front/e/9/e9cba32b-bfac-40cc-9f74-32d149740ac5.jpg',
        similarityScore: 88,
        role: 'cheapest',
        whySimilar: 'Colorless artifact providing a free, instant-speed sacrifice outlet.',
        whatItDoesDifferently: 'Stores charge counters to spawn 2/2 creatures rather than generating mana directly.',
        advantages: ['Costs only 2 mana ({2}) to cast', 'Costs under $0.50', 'Repopulates board after wraths'],
        disadvantages: ['Does not generate immediate mana'],
        idealDeckSituation: 'Aristocrat decks wanting board wipe resilience and free death triggers.',
      },
    ],
    relatedHubSlug: 'staples',
    relatedCategoryName: 'Sacrifice Outlets & Combo Engines',
  },

  'chaos-warp': {
    cardName: 'Chaos Warp',
    cleanSlug: 'chaos-warp',
    marketPrice: 0.85,
    manaValue: 3,
    colorIdentity: ['R'],
    typeLine: 'Instant',
    oracleText: 'The owner of target permanent shuffles it into their library, then reveals the top card of their library. If it\'s a permanent card, they put it onto the battlefield.',
    imageUri: 'https://cards.scryfall.io/normal/front/a/a/aa3f4e64-07d2-4322-a746-81c8286a11e1.jpg',
    cardRole: 'Universal Instant-Speed Permanent Removal',
    summaryProblem: 'Chaos Warp is Red’s signature answer to any permanent on the board (including troublesome enchantments). Players frequently search for cards with identical versatility, instant speed, and tuck mechanics across other colors and budget price points.',
    whyExpensive: 'A staple in virtually all Red Commander decks due to Red\'s historical inability to cleanly remove enchantments.',
    bestOverallReason: 'Wild Magic Surge answers any target permanent for only 2 mana ({1}{R}) at instant speed.',
    cheapestReason: 'Tibalt\'s Trickery ($1.20) and Abrade ($0.20) provide lean Red interaction.',
    closestFunctionalReason: 'Wild Magic Surge & Stroke of Midnight cleanly hit any problem permanent.',
    whenNotToSwap: 'Chaos Warp remains one of the best Red removal spells in the format and should often be run alongside Wild Magic Surge.',
    archetypeGuidance: [
      { archetype: 'Mono-Red / Izzet', recommendedCard: 'Wild Magic Surge', rationale: 'Hits any permanent for 1 less mana ({1}{R}) at instant speed.' },
      { archetype: 'Boros / Jeskai', recommendedCard: 'Stroke of Midnight', rationale: 'Destroys any nonland permanent and leaves a harmless 1/1 token.' },
      { archetype: 'Gruul / Jund', recommendedCard: 'Beast Within', rationale: 'Destroys ANY permanent (including lands) for {2}{G}.' },
    ],
    customFaqs: [
      { question: 'What cards are like Chaos Warp?', answer: 'Wild Magic Surge ($0.75), Beast Within ($0.95), Generous Gift ($0.65), and Stroke of Midnight ($0.60) are the closest functional equivalents to Chaos Warp.' },
      { question: 'Is Wild Magic Surge better than Chaos Warp?', answer: 'Wild Magic Surge costs 1 less mana ({1}{R} vs {2}{R}) and guarantees that the opponent only gets a card of the SAME permanent type, making it often better.' },
      { question: 'What makes Chaos Warp unique in Red?', answer: 'Red traditionally cannot destroy enchantments; Chaos Warp bypasses this by shuffling the target into the library rather than destroying it.' },
    ],
    alternatives: [
      {
        name: 'Wild Magic Surge',
        manaValue: 2,
        typeLine: 'Instant',
        priceUsd: 0.75,
        oracleText: 'Destroy target nonland permanent an opponent controls. That player reveals cards from the top of their library until they reveal a permanent card that shares a card type with the destroyed permanent, then puts that card onto the battlefield and the rest into their graveyard.',
        imageUri: 'https://cards.scryfall.io/normal/front/c/4/c4c89d88-9d40-46b6-bee8-500e23005779.jpg',
        similarityScore: 96,
        role: 'best_overall',
        whySimilar: 'Red instant-speed universal removal spell that replaces the permanent with a random top-deck card.',
        whatItDoesDifferently: 'Costs 1 less mana ({1}{R} vs {2}{R}) and only hits nonland permanents.',
        advantages: ['Cheaper 2-mana casting cost', 'Leaves no land advantage', 'Instant speed'],
        disadvantages: ['Cannot target your own permanents for fun polymorphs'],
        idealDeckSituation: 'Any Red Commander deck needing high-velocity spot removal.',
      },
      {
        name: 'Beast Within',
        manaValue: 3,
        typeLine: 'Instant',
        priceUsd: 0.95,
        oracleText: 'Destroy target permanent. Its controller creates a 3/3 green Beast creature token.',
        imageUri: 'https://cards.scryfall.io/normal/front/5/8/58888ea8-3841-4770-9831-294b0d061f00.jpg',
        similarityScore: 92,
        role: 'closest_functional',
        whySimilar: '3-mana instant that removes ANY permanent on the board and leaves a replacement body.',
        whatItDoesDifferently: 'Green color identity, and guarantees a simple 3/3 beast instead of random card flips.',
        advantages: ['Can destroy lands (Gaea\'s Cradle, Cabal Coffers)', 'Never flips an Eldrazi into play'],
        disadvantages: ['Requires Green mana'],
        idealDeckSituation: 'Green decks wanting unconditional interaction.',
      },
    ],
    relatedHubSlug: 'removal',
    relatedCategoryName: 'Targeted Removal Spells',
  },

  'show-and-tell': {
    cardName: 'Show and Tell',
    cleanSlug: 'show-and-tell',
    marketPrice: 16.50,
    manaValue: 3,
    colorIdentity: ['U'],
    typeLine: 'Sorcery',
    oracleText: 'Each player may put an artifact, creature, enchantment, or land card from their hand onto the battlefield.',
    imageUri: 'https://cards.scryfall.io/normal/front/f/a/fa7b7897-36e0-415a-8bb7-602886164852.jpg',
    cardRole: 'Hand-to-Battlefield Cheat / Hypergenesis Enabler',
    summaryProblem: 'Show and Tell is the gold standard for cheating 10-mana Eldrazi, Omniscience, or Blightsteel Colossus directly from hand into play for only 3 mana. At $16+, budget combo and big-mana players need alternative ways to cheat massive permanents.',
    whyExpensive: 'Legacy and Commander tournament staple enabling turn-2 and turn-3 game-ending combos.',
    bestOverallReason: 'Braids, Conjurer Adept provides a repeatable Show and Tell on a 4-drop creature body every upkeep.',
    cheapestReason: 'Elvish Piper ($1.80) and Quicksilver Amulet ($1.40) cheat massive creatures directly onto the battlefield for tap mana.',
    closestFunctionalReason: 'Hypergenesis and Eureka share the exact symmetrical hand-dump mechanics.',
    whenNotToSwap: 'In hyper-fast combo decks where casting a 3-mana sorcery on turn 2 to drop Omniscience is the primary win condition.',
    archetypeGuidance: [
      { archetype: 'Simic / Big Mana', recommendedCard: 'Braids, Conjurer Adept', rationale: 'Drops huge leviathans, artifacts, and lands every turn cycle for free.' },
      { archetype: 'Sneak & Attack', recommendedCard: 'Through the Breach', rationale: 'Gives the cheated creature Haste and instant-speed deployment.' },
      { archetype: 'Artifact / Colorless', recommendedCard: 'Quicksilver Amulet', rationale: 'Uncounterable tap ability putting creatures directly into play.' },
    ],
    customFaqs: [
      { question: 'What cards are like Show and Tell in MTG?', answer: 'Braids, Conjurer Adept ($1.50), Hypergenesis ($1.20), Eureka, Through the Breach ($4.50), and Quicksilver Amulet ($1.40) cheat permanents from hand to play.' },
      { question: 'What is the best budget alternative to Show and Tell?', answer: 'Braids, Conjurer Adept ($1.50) is the best budget alternative in Blue, putting an artifact, creature, or land into play every upkeep.' },
      { question: 'Is Show and Tell symmetrical in Commander?', answer: 'Yes! Every opponent gets to put a card into play as well, which is why decks build around overwhelmingly high-impact cards like Omniscience.' },
    ],
    alternatives: [
      {
        name: 'Braids, Conjurer Adept',
        manaValue: 4,
        typeLine: 'Legendary Creature — Human Wizard',
        priceUsd: 1.50,
        oracleText: 'At the beginning of each player\'s upkeep, that player may put an artifact, creature, or land card from their hand onto the battlefield.',
        imageUri: 'https://cards.scryfall.io/normal/front/9/e/9ea0e9e6-304e-4bcb-b30b-0d92095f9226.jpg',
        similarityScore: 94,
        role: 'best_overall',
        whySimilar: 'Blue permanent allowing players to put huge artifacts, creatures, and lands directly from hand into play.',
        whatItDoesDifferently: 'Repeatable trigger every upkeep on a creature body instead of a one-shot sorcery.',
        advantages: ['Repeatable value every turn cycle', 'Can serve as your Commander', 'Costs only $1.50 (90% savings)'],
        disadvantages: ['Opponents get the trigger on their upkeep before you if cast at sorcery speed'],
        idealDeckSituation: 'Big-mana Blue decks, sea monster tribal, and group hug.',
      },
    ],
    relatedHubSlug: 'deck-building',
    relatedCategoryName: 'Combo & Cheat Engines',
  },

  'cyclonic-rift': {
    cardName: 'Cyclonic Rift',
    cleanSlug: 'cyclonic-rift',
    marketPrice: 38.00,
    manaValue: 2,
    colorIdentity: ['U'],
    typeLine: 'Instant',
    oracleText: 'Return target nonland permanent you don\'t control to its owner\'s hand.\nOverload {6}{U} (You may cast this spell for its overload cost. If you do, change its text by replacing all instances of "target" with "each".)',
    imageUri: 'https://cards.scryfall.io/normal/front/f/5/f511a811-59e8-4903-8418-500b58e72792.jpg',
    cardRole: 'Instant-Speed Asymmetrical Nonland Board Wipe',
    summaryProblem: 'Cyclonic Rift is Blue’s undisputed #1 staple. Overloading it for 7 mana at instant speed clears all opponent tokens, mana rocks, blockers, and commanders while leaving your own board completely untouched. At $38+, budget decks need effective one-sided sweepers.',
    whyExpensive: 'Unmatched modal versatility (2-mana spot bounce or 7-mana instant game-winning one-sided wipe) with zero deckbuilding restriction.',
    bestOverallReason: 'Wash Out resets entire color alignments for only 4 mana, often blowing out 2–3 opponents while sparing your own key pieces.',
    cheapestReason: 'Aetherize ($0.45) and Spectral Deluge ($0.65) bounce entire attacking armies and nonland boards for pennies.',
    closestFunctionalReason: 'Evacuation & River\'s Rebuke provide dedicated mass bounce at instant and sorcery speed.',
    whenNotToSwap: 'In high-power pods where holding up 7 mana for an instant-speed, one-sided wipe on opponent end step is essential for victory.',
    archetypeGuidance: [
      { archetype: 'Mono-Blue / Islands', recommendedCard: 'Spectral Deluge', rationale: 'Foretell 3-mana sorcery that bounces all opponent creatures based on Island count.' },
      { archetype: 'Tempo / Control', recommendedCard: 'Aetherize', rationale: 'Instant-speed 4-mana blowout that bounces all attacking creatures.' },
      { archetype: 'Multi-Color / Sorcery', recommendedCard: 'Wash Out', rationale: 'Calls a dominant color like Green or White and wipes out 80% of the table.' },
    ],
    customFaqs: [
      { question: 'What is the best budget alternative to Cyclonic Rift?', answer: 'Wash Out ($1.20) and Spectral Deluge ($0.65) are the top budget alternatives, clearing opponent boards for 4 mana or less.' },
      { question: 'What is the cheapest instant-speed bounce wipe?', answer: 'Aetherize ($0.45) and Evacuation ($0.60) provide instant-speed mass creature bounce under $1.00.' },
      { question: 'Can Wash Out replace Cyclonic Rift?', answer: 'Yes! Wash Out costs only {3}{U} and returns all permanents of a chosen color (including tokens and planeswalkers) to hand.' },
    ],
    alternatives: [
      {
        name: 'Wash Out',
        manaValue: 4,
        typeLine: 'Sorcery',
        priceUsd: 1.20,
        oracleText: 'Return all permanents of the color of your choice to their owners\' hands.',
        imageUri: 'https://cards.scryfall.io/normal/front/0/2/02967ea7-3069-4e78-9e20-31804f05256e.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: 'Blue mass bounce spell targeting nonland permanents across all opponents.',
        whatItDoesDifferently: 'Sorcery speed and filters by color identity rather than overload.',
        advantages: ['Costs only 4 mana ({3}{U}) compared to Rift\'s 7-mana overload', 'Clears artifacts, enchantments, and planeswalkers of that color'],
        disadvantages: ['Sorcery speed', 'Can hit your own permanents if you share the chosen color'],
        idealDeckSituation: 'Multiplayer games with dominant green or white token/enchantment boards.',
      },
      {
        name: 'Aetherize',
        manaValue: 4,
        typeLine: 'Instant',
        priceUsd: 0.45,
        oracleText: 'Return all attacking creatures to their owners\' hands.',
        imageUri: 'https://cards.scryfall.io/normal/front/a/0/a029a738-f9b9-4786-8a03-911e86a07604.jpg',
        similarityScore: 89,
        role: 'cheapest',
        whySimilar: 'Instant-speed blue mass bounce that leaves your own board completely intact.',
        whatItDoesDifferently: 'Only bounces attacking creatures during combat.',
        advantages: ['Instant speed for only 4 mana ({3}{U})', 'Costs under $0.50 (99% savings)', 'Completely destroys token armies'],
        disadvantages: ['Does not bounce utility permanents or non-attacking creatures'],
        idealDeckSituation: 'Defensive control decks that need instant combat protection.',
      },
    ],
    relatedHubSlug: 'board-wipes',
    relatedCategoryName: 'Board Wipes & Mass Bounce',
  },

  'the-one-ring': {
    cardName: 'The One Ring',
    cleanSlug: 'the-one-ring',
    marketPrice: 95.00,
    manaValue: 4,
    colorIdentity: [],
    typeLine: 'Legendary Artifact',
    oracleText: 'Indestructible\nWhen The One Ring enters the battlefield, if you cast it, you gain protection from everything until your next turn.\n{T}, Put a burden counter on The One Ring: Draw a card for each burden counter on The One Ring.\nAt the beginning of your upkeep, you lose 1 life for each burden counter on The One Ring.',
    imageUri: 'https://cards.scryfall.io/normal/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg',
    cardRole: 'Colorless Card Advantage & Protection Engine',
    summaryProblem: 'The One Ring provides unprecedented turn-one protection and exponential card draw that fits into literally every MTG deck. At $95–$100+, budget players need colorless card advantage engines that draw multiple cards per turn cycle.',
    whyExpensive: 'Unmatched power in Modern, Commander, and Legacy due to ETB protection + drawing 1, 2, 3, 4+ cards every tap.',
    bestOverallReason: 'Palantír of Orthanc & Staff of Compleation offer colorless turn-by-turn card advantage and mana utility.',
    cheapestReason: 'Loreseeker\'s Stone ($0.28) and Tome of Legends ($0.45) draw 3 cards or trigger off commander attacks for pennies.',
    closestFunctionalReason: 'Staff of Compleation combines tap-activated card draw with life payment in a 3-CMC artifact.',
    whenNotToSwap: 'In top-tier competitive cEDH/Modern where the ETB "protection from everything" is required to survive lethal attack turns.',
    archetypeGuidance: [
      { archetype: 'Artifact Heavy / Proliferate', recommendedCard: 'Staff of Compleation', rationale: 'Draws cards, proliferates counters, and ramps mana on tap.' },
      { archetype: 'Commander Centric', recommendedCard: 'Tome of Legends', rationale: 'Draws a card for 1 mana whenever your commander enters or attacks.' },
      { archetype: 'Colorless / Big Mana', recommendedCard: 'Loreseeker\'s Stone', rationale: 'Draws 3 cards every turn cycle once your hand empties.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to The One Ring?', answer: 'Staff of Compleation ($4.20) and Palantír of Orthanc ($12.00) are the best colorless card draw engines in MTG.' },
      { question: 'What is the cheapest card draw artifact like The One Ring?', answer: 'Loreseeker\'s Stone ($0.28) and Tome of Legends ($0.45) cost under $0.50 and provide repeatable tap-to-draw utility.' },
    ],
    alternatives: [
      {
        name: 'Staff of Compleation',
        manaValue: 3,
        typeLine: 'Artifact',
        priceUsd: 4.20,
        oracleText: '{T}, Pay 1 life: Destroy target permanent you own.\n{T}, Pay 2 life: Add one mana of any color.\n{T}, Pay 3 life: Proliferate.\n{T}, Pay 4 life: Draw a card.',
        imageUri: 'https://cards.scryfall.io/normal/front/d/2/d2934af5-aa4f-4c88-adbd-d424e0475573.jpg',
        similarityScore: 91,
        role: 'best_overall',
        whySimilar: 'Colorless artifact that pays life to draw cards on tap.',
        whatItDoesDifferently: 'Costs 1 less mana (3 CMC vs 4 CMC), also acts as a mana rock and proliferate engine.',
        advantages: ['Costs only 3 mana', 'Flexible utility (ramp, sacrifice, proliferate, draw)', 'Zero burden counter scaling'],
        disadvantages: ['Requires 4 life per draw', 'Lacks protection from everything'],
        idealDeckSituation: 'Artifact, life gain, or proliferate decks.',
      },
      {
        name: 'Loreseeker\'s Stone',
        manaValue: 6,
        typeLine: 'Artifact',
        priceUsd: 0.28,
        oracleText: '{3}, {T}: Draw three cards. This ability costs {1} more to activate for each card in your hand.',
        imageUri: 'https://cards.scryfall.io/normal/front/e/9/e93b1626-d463-4688-8508-30002779b5ab.jpg',
        similarityScore: 85,
        role: 'cheapest',
        whySimilar: 'Colorless artifact providing tap-activated burst card draw.',
        whatItDoesDifferently: 'Costs 6 mana to cast and draws 3 cards at once.',
        advantages: ['Draws 3 cards per tap', 'Costs under $0.30 (99% savings)'],
        disadvantages: ['Costs 6 mana to cast', 'Activation cost increases with cards in hand'],
        idealDeckSituation: 'Aggro or storm decks that empty their hand quickly.',
      },
    ],
    relatedHubSlug: 'card-draw',
    relatedCategoryName: 'Colorless Card Advantage',
  },

  'jeskas-will': {
    cardName: 'Jeska\'s Will',
    cleanSlug: 'jeskas-will',
    marketPrice: 19.50,
    manaValue: 3,
    colorIdentity: ['R'],
    typeLine: 'Sorcery',
    oracleText: 'Choose one. If you control a commander as you cast this spell, you may choose both.\n• Add {R} for each card in target opponent\'s hand.\n• Exile the top three cards of your library. You may play them this turn.',
    imageUri: 'https://cards.scryfall.io/normal/front/4/e/4e91d96d-cc69-439b-b876-a7d57039022c.jpg',
    cardRole: 'Explosive Ritual Ramp & Impulse Draw Engine',
    summaryProblem: 'Jeska\'s Will is Red\'s most explosive 3-mana spell, frequently generating 6–8 red mana AND impulse-drawing 3 cards in one cast. At nearly $20, budget players need alternative red rituals and burst impulse advantage.',
    whyExpensive: 'Unmatched 3-mana acceleration in Commander that simultaneously fixes mana and refills hand resources.',
    bestOverallReason: 'Mana Geyser generates massive amounts of red mana (often 15–20+ mana) in multiplayer games for {4}{R}.',
    cheapestReason: 'Seething Song ($1.80) and Pyretic Ritual ($1.50) provide reliable mana boosts under $2.',
    closestFunctionalReason: 'Birgi, God of Storytelling & Brass\'s Bounty generate continuous burst mana and card impulse.',
    whenNotToSwap: 'When your deck relies on a 3-mana storm turn to cast your commander and win immediately.',
    archetypeGuidance: [
      { archetype: 'Storm / Spellslinger', recommendedCard: 'Mana Geyser', rationale: 'Taps into 15–25 mana on turn 5 to fuel a game-winning combo.' },
      { archetype: 'Impulse / Card Draw', recommendedCard: 'Light Up the Stage', rationale: 'Exiles 2 cards for only {R} with Spectacle.' },
      { archetype: 'Treasure / Artifact', recommendedCard: 'Brass\'s Bounty', rationale: 'Converts land count into permanent colored treasure mana.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Jeska\'s Will?', answer: 'Mana Geyser ($1.90) is the best ritual replacement, generating 10–25 mana in 4-player Commander games.' },
      { question: 'What cards are like Jeska\'s Will in MTG?', answer: 'Seething Song, Mana Geyser, Brass\'s Bounty, Birgi Front, and Light Up the Stage.' },
    ],
    alternatives: [
      {
        name: 'Mana Geyser',
        manaValue: 5,
        typeLine: 'Sorcery',
        priceUsd: 1.90,
        oracleText: 'Add {R} for each tapped land your opponents control.',
        imageUri: 'https://cards.scryfall.io/normal/front/1/0/10944732-9177-474c-a7ac-23ea0fb77030.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: 'Red sorcery generating huge spikes of red mana based on opponent board states.',
        whatItDoesDifferently: 'Costs 5 mana ({4}{R}) and counts opponent tapped lands rather than cards in hand.',
        advantages: ['Regularly produces 15 to 25+ red mana in multiplayer EDH', 'Costs under $2.00 (90% savings)'],
        disadvantages: ['Costs 5 mana to cast', 'Does not impulse draw cards'],
        idealDeckSituation: 'Big-mana, Dragon, Storm, or X-spell finisher decks.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Red Rituals & Ramp',
  },

  'seedborn-muse': {
    cardName: 'Seedborn Muse',
    cleanSlug: 'seedborn-muse',
    marketPrice: 11.50,
    manaValue: 5,
    colorIdentity: ['G'],
    typeLine: 'Creature — Spirit',
    oracleText: 'Untap all permanents you control during each other player\'s untap step.',
    imageUri: 'https://cards.scryfall.io/normal/front/3/f/3f5bee0f-ebc8-4f41-91ee-4eed104ad980.jpg',
    cardRole: 'Every-Turn Permanent Untap Engine',
    summaryProblem: 'Seedborn Muse effectively quadruples your mana in Commander by untapping all your lands, creatures, and artifacts during EVERY opponent’s untap step. At $11+, budget decks need alternative ways to untap resources on opponent turns.',
    whyExpensive: 'Premier engine for flash commanders, instant-speed interaction, and activated abilities.',
    bestOverallReason: 'Wilderness Reclamation untaps all your lands at your end step for only 4 mana, providing a second full turn of mana.',
    cheapestReason: 'Awakening ($2.80) and Murkfiend Liege ($1.50) untap permanents and creatures consistently.',
    closestFunctionalReason: 'Unwinding Clock untaps all artifacts (including mana rocks) on every untap step.',
    whenNotToSwap: 'In decks running Thrasios, Tasigur, or Kenrith that need to sink 15+ mana into commander activations every single opponent turn.',
    archetypeGuidance: [
      { archetype: 'Spellslinger / Control', recommendedCard: 'Wilderness Reclamation', rationale: 'Untaps all lands at end of turn to hold open interaction.' },
      { archetype: 'Artifact / Mana Rocks', recommendedCard: 'Unwinding Clock', rationale: 'Untaps all mana rocks, artifact creatures, and utility artifacts on every untap step.' },
      { archetype: 'Simic / Selesnya Creatures', recommendedCard: 'Murkfiend Liege', rationale: 'Untaps your blue/green creatures on opponent turns while buffing power by +2/+2.' },
    ],
    customFaqs: [
      { question: 'What is the best budget alternative to Seedborn Muse?', answer: 'Wilderness Reclamation ($1.80) and Murkfiend Liege ($1.50) are the top budget alternatives.' },
      { question: 'What cards untap your board on opponent turns?', answer: 'Unwinding Clock ($8), Wilderness Reclamation ($1.80), Murkfiend Liege ($1.50), and Awakening ($2.80).' },
    ],
    alternatives: [
      {
        name: 'Wilderness Reclamation',
        manaValue: 4,
        typeLine: 'Enchantment',
        priceUsd: 1.80,
        oracleText: 'At the beginning of your end step, untap all lands you control.',
        imageUri: 'https://cards.scryfall.io/normal/front/2/7/27598868-53ce-4228-a59e-99894777f4d7.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: 'Green permanent providing massive land untapping for instant-speed turns.',
        whatItDoesDifferently: 'Untaps lands once on your end step rather than on every opponent turn.',
        advantages: ['Harder to remove than a creature (Enchantment type)', 'Costs 1 less mana (4 CMC vs 5 CMC)'],
        disadvantages: ['Only untaps lands (not artifacts or creatures)'],
        idealDeckSituation: 'Flash, control, and X-spell decks holding up mana on end step.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Untap Engines & Mana Doublers',
  },

  'senseis-divining-top': {
    cardName: 'Sensei\'s Divining Top',
    cleanSlug: 'senseis-divining-top',
    marketPrice: 24.00,
    manaValue: 1,
    colorIdentity: [],
    typeLine: 'Artifact',
    oracleText: '{1}: Look at the top three cards of your library, then put them back in any order.\n{T}: Draw a card, then put Sensei\'s Divining Top on top of its owner\'s library.',
    imageUri: 'https://cards.scryfall.io/normal/front/e/5/e5142b7a-e580-4737-a0aa-2599f6d0a77d.jpg',
    cardRole: 'Repeatable Top-Deck Manipulation & Card Draw Engine',
    summaryProblem: 'Sensei\'s Divining Top provides unmatched topdeck control for 1 mana and forms infinite draw loops with Bolas\'s Citadel and cost reducers. At $24+, budget players need reliable library filtering and topdeck manipulation.',
    whyExpensive: 'Infinite combo staple with Citadel, Elsha, and Mystic Forge, plus universal 1-mana colorless slot in any deck.',
    bestOverallReason: 'Crystal Ball scrys 2 cards for {1} every turn on a 3-drop artifact without putting itself back on top.',
    cheapestReason: 'Darksteel Pendant ($0.25) and Soothsaying ($1.20) filter topdecks for pennies.',
    closestFunctionalReason: 'Scroll Rack & Mirrormade provide deep hand-and-library swaps.',
    whenNotToSwap: 'If your combo specifically requires an artifact that taps to draw and puts itself on top of library to execute an infinite loop with Bolas\'s Citadel.',
    archetypeGuidance: [
      { archetype: 'Topdeck Matters (Yennett / Yuriko)', recommendedCard: 'Soothsaying', rationale: 'Manipulates top X cards at instant speed for any amount of mana.' },
      { archetype: 'Artifact Synergy', recommendedCard: 'Crystal Ball', rationale: 'Repeatable Scry 2 on an artifact permanent.' },
      { archetype: 'Miracle / Control', recommendedCard: 'Brainstorm', rationale: 'Instant-speed topdeck setup for 1 blue mana.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Sensei\'s Divining Top?', answer: 'Crystal Ball ($0.35) and Soothsaying ($1.20) are the best direct replacements for library manipulation.' },
      { question: 'How do you replace the Bolas\'s Citadel + Top combo on a budget?', answer: 'Aetherflux Reservoir + Necropotence or Citadel + Mortuary/Gravecrawler can replace the loop without Top.' },
    ],
    alternatives: [
      {
        name: 'Crystal Ball',
        manaValue: 3,
        typeLine: 'Artifact',
        priceUsd: 0.35,
        oracleText: '{1}, {T}: Scry 2.',
        imageUri: 'https://cards.scryfall.io/normal/front/d/4/d44e0170-9390-4829-b8fb-8958ea3c4e4b.jpg',
        similarityScore: 90,
        role: 'best_overall',
        whySimilar: 'Colorless artifact that pays {1} and taps to filter the top cards of library.',
        whatItDoesDifferently: 'Scrys 2 (can bottom unwanted cards) instead of looking at top 3.',
        advantages: ['Can bottom dead cards permanently', 'Costs under $0.50 (98% savings)'],
        disadvantages: ['Costs 3 mana to cast', 'Does not draw a card on tap'],
        idealDeckSituation: 'Control, topdeck matters, and miracle decks.',
      },
    ],
    relatedHubSlug: 'tutors',
    relatedCategoryName: 'Topdeck Filtering & Tutors',
  },

  'the-great-henge': {
    cardName: 'The Great Henge',
    cleanSlug: 'the-great-henge',
    marketPrice: 48.00,
    manaValue: 9,
    colorIdentity: ['G'],
    typeLine: 'Legendary Artifact',
    oracleText: 'This spell costs {X} less to cast, where X is the greatest power among creatures you control.\n{T}: Add {G}{G}. You gain 2 life.\nWhenever a nontoken creature enters the battlefield under your control, put a +1/+1 counter on it and draw a card.',
    imageUri: 'https://cards.scryfall.io/normal/front/a/f/af915ed2-1f34-43f6-85f5-2430325b720f.jpg',
    cardRole: 'Cost-Reduced Ramp, Creature Draw & +1/+1 Buff Engine',
    summaryProblem: 'The Great Henge regularly costs only {G}{G} in green stompy decks, tapping for 2 mana, gaining life, buffing every creature with +1/+1 counters, and drawing cards on every entry. At $48+, budget green players need comparable creature-draw engines.',
    whyExpensive: 'Unmatched 4-in-1 value (ramp, life gain, +1/+1 counters, continuous draw) that costs only 2 mana when you have a big creature.',
    bestOverallReason: 'Tribute to the World Tree provides continuous draw and +1/+1 counters for only {G}{G}{G}.',
    cheapestReason: 'Garruk\'s Uprising ($0.45) and Elemental Bond ($1.50) draw cards on creature entries for pennies.',
    closestFunctionalReason: 'Rishkar\'s Expertise & Return of the Wildspeaker convert creature power into massive draw bursts.',
    whenNotToSwap: 'In green creature decks looking for an all-in-one artifact that provides both ramp and creature draw on a single card.',
    archetypeGuidance: [
      { archetype: 'Stompy / Power 4+', recommendedCard: 'Garruk\'s Uprising', rationale: 'Grants entire board trample, draws on entry, and draws whenever big creatures enter.' },
      { archetype: 'Mono-Green Devotion', recommendedCard: 'Tribute to the World Tree', rationale: 'Puts two counters on small creatures or draws cards on 3+ power creatures.' },
      { archetype: 'Burst Draw / Finishers', recommendedCard: 'Return of the Wildspeaker', rationale: 'Instant-speed draw equal to greatest power or +3/+3 overrun pump.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to The Great Henge?', answer: 'Tribute to the World Tree ($4.50) and Garruk\'s Uprising ($0.45) are the top budget alternatives.' },
      { question: 'What green cards draw cards when creatures enter?', answer: 'Beast Whisperer ($1.50), Guardian Project ($9.00), Elemental Bond ($1.50), and Garruk\'s Uprising ($0.45).' },
    ],
    alternatives: [
      {
        name: 'Garruk\'s Uprising',
        manaValue: 3,
        typeLine: 'Enchantment',
        priceUsd: 0.45,
        oracleText: 'When Garruk\'s Uprising enters the battlefield, if you control a creature with power 4 or greater, draw a card.\nCreatures you control have trample.\nWhenever a creature with power 4 or greater enters the battlefield under your control, draw a card.',
        imageUri: 'https://cards.scryfall.io/normal/front/9/8/98795a31-7b54-4ad1-ac87-3f58e71dbeb7.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: '3-CMC green enchantment providing ETB card draw and passive team-wide buffs.',
        whatItDoesDifferently: 'Grants trample rather than +1/+1 counters and requires 4+ power to trigger.',
        advantages: ['Costs only 3 mana ({2}{G})', 'Costs under $0.50 (99% savings)', 'Grants universal trample'],
        disadvantages: ['Does not produce mana', 'Does not trigger on 1–3 power creatures'],
        idealDeckSituation: 'Green stompy, dinosaur, and dragon creature decks.',
      },
    ],
    relatedHubSlug: 'card-draw',
    relatedCategoryName: 'Green Card Advantage',
  },

  'sea-gate-restoration': {
    cardName: 'Sea Gate Restoration // Sea Gate, Reborn',
    cleanSlug: 'sea-gate-restoration',
    marketPrice: 17.50,
    manaValue: 7,
    colorIdentity: ['U'],
    typeLine: 'Sorcery // Land',
    oracleText: 'Draw cards equal to the number of cards in your hand plus one. You have no maximum hand size for the rest of the game.',
    imageUri: 'https://cards.scryfall.io/normal/front/1/9/193071fe-180b-4d35-ba78-9c16675c29fc.jpg',
    cardRole: 'MDFC Untapped Land & Double-Hand Burst Draw',
    summaryProblem: 'Sea Gate Restoration is the premier Blue Modal Double-Faced Card (MDFC), taking up a land slot with zero deckbuilding cost while serving as a 7-mana burst draw engine late game. At $17+, budget deck builders need high-volume blue draw spells and utility lands.',
    whyExpensive: 'Occupies a land slot with virtually zero opportunity cost across Commander and Modern.',
    bestOverallReason: 'Flow of Knowledge & Peer into the Abyss draw massive chunks of your library for 5–7 mana.',
    cheapestReason: 'Reliquary Tower ($1.20) on land slot + Flow of Knowledge ($0.25) provides the exact same effect.',
    closestFunctionalReason: 'Rush of Knowledge & Overflowing Insight provide direct high-volume draw.',
    whenNotToSwap: 'In hyper-optimized competitive lists where MDFC land count is maximized to avoid drawing dead spells.',
    archetypeGuidance: [
      { archetype: 'Mono-Blue / Control', recommendedCard: 'Flow of Knowledge', rationale: 'Instant-speed draw equal to your Island count.' },
      { archetype: 'Big Mana / Hand Size', recommendedCard: 'Reliquary Tower', rationale: 'Grants no maximum hand size directly on an untapped land slot.' },
    ],
    customFaqs: [
      { question: 'What is the best budget alternative to Sea Gate Restoration?', answer: 'Flow of Knowledge ($0.25) combined with Reliquary Tower ($1.20) reproduces both halves of Sea Gate Restoration for under $1.50.' },
    ],
    alternatives: [
      {
        name: 'Flow of Knowledge',
        manaValue: 5,
        typeLine: 'Instant',
        priceUsd: 0.25,
        oracleText: 'Draw a card for each Island you control, then discard two cards.',
        imageUri: 'https://cards.scryfall.io/normal/front/5/e/5ea316f3-4a68-4856-837f-ab720187423f.jpg',
        similarityScore: 89,
        role: 'best_overall',
        whySimilar: 'High-volume blue draw spell drawing 5–8+ cards.',
        whatItDoesDifferently: 'Instant speed and costs 2 less mana ({4}{U} vs 7 CMC).',
        advantages: ['Instant speed', 'Costs 2 less mana', 'Costs under $0.30'],
        disadvantages: ['Not an MDFC land'],
        idealDeckSituation: 'Mono-blue or high-island-count Commander decks.',
      },
    ],
    relatedHubSlug: 'card-draw',
    relatedCategoryName: 'Blue Burst Draw',
  },

  'mox-opal': {
    cardName: 'Mox Opal',
    cleanSlug: 'mox-opal',
    marketPrice: 75.00,
    manaValue: 0,
    colorIdentity: [],
    typeLine: 'Legendary Artifact',
    oracleText: 'Metalcraft — {T}: Add one mana of any color. Activate only if you control three or more artifacts.',
    imageUri: 'https://cards.scryfall.io/normal/front/5/6/56001a36-126b-4c08-af98-a6cc4964210e.jpg',
    cardRole: 'Zero-Mana Colored Fast Mana Artifact',
    summaryProblem: 'Mox Opal is the premier 0-mana colored mana rock in artifact decks. At $75+, budget artifact and cheerios deck builders need cheap mana rocks and fast mana enablers.',
    whyExpensive: 'Zero mana cost with repeatable colored mana fixing in modern and cEDH artifact decks.',
    bestOverallReason: 'Springleaf Drum & Paradise Mantle provide 1-drop mana acceleration in creature/artifact decks.',
    cheapestReason: 'Moonsnare Prototype ($0.25) and Springleaf Drum ($0.65) tap artifacts for mana.',
    closestFunctionalReason: 'Lotus Petal ($18) and Paradise Mantle ($1.20) produce colored mana for 0–1 mana.',
    whenNotToSwap: 'In cEDH artifact storm where 0-mana colored acceleration on turn 1 is required.',
    archetypeGuidance: [
      { archetype: 'Artifact Swarm / Affinity', recommendedCard: 'Moonsnare Prototype', rationale: 'Taps artifacts or creatures for mana, and can be channeled to bounce threats.' },
      { archetype: 'Creature Aggro', recommendedCard: 'Springleaf Drum', rationale: 'Taps 1-drop creatures for colored mana on turn 1.' },
    ],
    customFaqs: [
      { question: 'What is the best budget alternative to Mox Opal?', answer: 'Springleaf Drum ($0.65) and Moonsnare Prototype ($0.25) are the top budget alternatives for artifact mana ramp.' },
    ],
    alternatives: [
      {
        name: 'Springleaf Drum',
        manaValue: 1,
        typeLine: 'Artifact',
        priceUsd: 0.65,
        oracleText: '{T}, Tap an untapped creature you control: Add one mana of any color.',
        imageUri: 'https://cards.scryfall.io/normal/front/f/3/f3b3869b-6da1-4b01-a2e7-2018d478b6e5.jpg',
        similarityScore: 90,
        role: 'best_overall',
        whySimilar: 'Cheap artifact generating any color of mana on tap.',
        whatItDoesDifferently: 'Costs 1 mana to cast and requires tapping a creature.',
        advantages: ['Fixes all 5 colors of mana', 'Costs under $1.00 (99% savings)'],
        disadvantages: ['Requires 1 mana to cast and a creature body'],
        idealDeckSituation: 'Low-curve creature and artifact decks.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Fast Mana & Mana Rocks',
  },

  'sheoldred-the-apocalypse': {
    cardName: 'Sheoldred, the Apocalypse',
    cleanSlug: 'sheoldred-the-apocalypse',
    marketPrice: 68.00,
    manaValue: 4,
    colorIdentity: ['B'],
    typeLine: 'Legendary Creature — Phyrexian Praetor',
    oracleText: 'Deathtouch\nWhenever you draw a card, you gain 2 life.\nWhenever an opponent draws a card, they lose 2 life.',
    imageUri: 'https://cards.scryfall.io/normal/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
    cardRole: 'Draw-Punishment & Life Drain Engine',
    summaryProblem: 'Sheoldred, the Apocalypse weaponizes the card draw phase, punishing opponents for 2 life per card drawn while padding your life total. At $68+, budget Black players need effective draw-punishment and group slug engines.',
    whyExpensive: 'Dominates Standard, Pioneer, and Commander with an enormous life swing every turn cycle.',
    bestOverallReason: 'Underworld Dreams & Fate Unraveler punish every opponent draw for 1 damage on cheap 3–4 CMC permanents.',
    cheapestReason: 'Underworld Dreams ($0.75) and Ob Nixilis, the Hate-Forged ($0.65) punish card draw under $1.',
    closestFunctionalReason: 'Fate Unraveler is a 4-CMC creature that drains 1 life per opponent card draw.',
    whenNotToSwap: 'If your strategy relies on the +2 life gain per draw to fuel Necropotence or Bolas\'s Citadel.',
    archetypeGuidance: [
      { archetype: 'Wheels / Nekusar', recommendedCard: 'Fate Unraveler', rationale: 'Drains 7 damage per player whenever a Windfall or Wheel of Fortune resolves.' },
      { archetype: 'Mono-Black Control', recommendedCard: 'Underworld Dreams', rationale: 'Enchantment that is hard to remove and continuously bleeds opponents.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Sheoldred the Apocalypse?', answer: 'Fate Unraveler ($1.20) and Underworld Dreams ($0.75) are the top budget alternatives for draw punishment.' },
    ],
    alternatives: [
      {
        name: 'Fate Unraveler',
        manaValue: 4,
        typeLine: 'Enchantment Creature — Hag',
        priceUsd: 1.20,
        oracleText: 'Whenever an opponent draws a card, Fate Unraveler deals 1 damage to that player.',
        imageUri: 'https://cards.scryfall.io/normal/front/1/e/1e2a9dea-349b-4e23-a66f-e9a2585f472f.jpg',
        similarityScore: 92,
        role: 'best_overall',
        whySimilar: '4-CMC black creature that punishes opponents every time they draw a card.',
        whatItDoesDifferently: 'Deals 1 damage instead of 2 life loss, and does not gain you life.',
        advantages: ['Costs only $1.20 (98% savings)', 'Shares 4-CMC mana curve'],
        disadvantages: ['Deals 1 damage per draw instead of 2', 'Does not gain you life'],
        idealDeckSituation: 'Wheel decks, group slug, and Nekusar Commander lists.',
      },
    ],
    relatedHubSlug: 'staples',
    relatedCategoryName: 'Group Slug & Life Drain',
  },

  'enlightened-tutor': {
    cardName: 'Enlightened Tutor',
    cleanSlug: 'enlightened-tutor',
    marketPrice: 20.00,
    manaValue: 1,
    colorIdentity: ['W'],
    typeLine: 'Instant',
    oracleText: 'Search your library for an artifact or enchantment card, reveal it, then shuffle and put that card on top of your library.',
    imageUri: 'https://cards.scryfall.io/normal/front/0/c/0c070f12-0f5f-4a00-9a3b-b83b320d3674.jpg',
    cardRole: '1-Mana Instant Artifact/Enchantment Tutor',
    summaryProblem: 'Enlightened Tutor finds game-winning combo pieces like Smothering Tithe, Rhystic Study, or Bolas\'s Citadel for 1 mana at instant speed. At $20+, budget White players need reliable search options.',
    whyExpensive: 'Unmatched 1-mana instant speed flexibility finding both artifacts and enchantments.',
    bestOverallReason: 'Idyllic Tutor & Moon-Blessed Cleric put key enchantments directly into hand or on top of library.',
    cheapestReason: 'Open the Armory ($0.35) and Moon-Blessed Cleric ($0.30) search for equipment, auras, and enchantments under $0.50.',
    closestFunctionalReason: 'Search for Glory finds legendary permanents (including artifacts and enchantments) and snow cards.',
    whenNotToSwap: 'When your deck requires 1-mana instant speed interaction to fetch an artifact combo piece on opponent end step.',
    archetypeGuidance: [
      { archetype: 'Enchantress', recommendedCard: 'Idyllic Tutor', rationale: 'Searches for ANY enchantment directly to hand for 3 mana.' },
      { archetype: 'Equipment / Voltron', recommendedCard: 'Open the Armory', rationale: 'Searches for any Equipment or Aura directly to hand for {1}{W}.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Enlightened Tutor?', answer: 'Idyllic Tutor ($3.50) and Moon-Blessed Cleric ($0.30) are the top budget alternatives for finding enchantments.' },
    ],
    alternatives: [
      {
        name: 'Moon-Blessed Cleric',
        manaValue: 3,
        typeLine: 'Creature — Human Elf Cleric',
        priceUsd: 0.30,
        oracleText: 'When Moon-Blessed Cleric enters the battlefield, you may search your library for an enchantment card, reveal it, then shuffle and put that card on top of your library.',
        imageUri: 'https://cards.scryfall.io/normal/front/2/b/2b7fea79-9600-41d7-b890-8ecf95a20c04.jpg',
        similarityScore: 91,
        role: 'best_overall',
        whySimilar: 'White permanent that searches for an enchantment and puts it on top of library.',
        whatItDoesDifferently: 'Sorcery-speed creature ETB instead of 1-mana instant.',
        advantages: ['Leaves a 3/2 creature body on the board', 'Costs under $0.50 (98% savings)'],
        disadvantages: ['Cannot search for artifacts', 'Costs 3 mana ({2}{W})'],
        idealDeckSituation: 'Enchantress, blink, and reanimator decks.',
      },
    ],
    relatedHubSlug: 'tutors',
    relatedCategoryName: 'Tutors & Search Spells',
  },

  'earthcraft': {
    cardName: 'Earthcraft',
    cleanSlug: 'earthcraft',
    marketPrice: 125.00,
    manaValue: 2,
    colorIdentity: ['G'],
    typeLine: 'Enchantment',
    oracleText: 'Tap an untapped creature you control: Untap target basic land.',
    imageUri: 'https://cards.scryfall.io/normal/front/9/d/9dda10a4-d060-47fd-b3b4-f370757a3d24.jpg',
    cardRole: 'Reserved List Free Creature-to-Land Untap Engine',
    summaryProblem: 'Earthcraft is a Reserved List legend, allowing you to tap ANY creature (even summoning sick tokens) to untap basic lands, creating infinite mana loops with Squirrel Nest and token producers. At $125+, budget players need viable tap-for-mana alternatives.',
    whyExpensive: 'Reserved list rarity combined with zero-mana infinite combo enabler status.',
    bestOverallReason: 'Cryptolith Rite turns every creature into a Birds of Paradise, tapping for any colored mana.',
    cheapestReason: 'Song of Freyalise ($0.45) and Citanul Hierophants ($1.50) grant all creatures mana-tapping abilities.',
    closestFunctionalReason: 'Badgermole Cub & Cryptolith Rite convert creature taps into explosive land and mana acceleration.',
    whenNotToSwap: 'If your combo strictly relies on tapping summoning sick tokens to untap a land with Squirrel Nest to produce infinite squirrels.',
    archetypeGuidance: [
      { archetype: 'Token Swarm', recommendedCard: 'Cryptolith Rite', rationale: 'Turns 20 1/1 tokens into 20 mana of any color.' },
      { archetype: 'Budget Combo', recommendedCard: 'Song of Freyalise', rationale: 'Ramps mana for 2 turns, then gives your whole board +1/+1 counters, vigilance, and indestructible.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Earthcraft in MTG?', answer: 'Cryptolith Rite ($9.50) and Song of Freyalise ($0.45) are the top budget alternatives, giving all your creatures the ability to tap for mana.' },
    ],
    alternatives: [
      {
        name: 'Cryptolith Rite',
        manaValue: 2,
        typeLine: 'Enchantment',
        priceUsd: 9.50,
        oracleText: 'Creatures you control have "{T}: Add one mana of any color."',
        imageUri: 'https://cards.scryfall.io/normal/front/2/9/2910adcd-882a-46af-8236-ca1a9e2c19ab.jpg',
        similarityScore: 94,
        role: 'best_overall',
        whySimilar: '2-CMC green enchantment converting all creatures into immediate mana acceleration.',
        whatItDoesDifferently: 'Creatures tap for mana directly (subject to summoning sickness) rather than untapping basic lands.',
        advantages: ['Produces ANY color of mana', 'Costs 92% less than Earthcraft'],
        disadvantages: ['Creatures cannot tap the turn they enter unless they have haste'],
        idealDeckSituation: 'Go-wide token and swarm Commander decks.',
      },
      {
        name: 'Song of Freyalise',
        manaValue: 2,
        typeLine: 'Enchantment — Saga',
        priceUsd: 0.45,
        oracleText: 'I, II — Until your next turn, creatures you control gain "{T}: Add one mana of any color."\nIII — Put a +1/+1 counter on each creature you control. Those creatures gain vigilance, trample, and indestructible until end of turn.',
        imageUri: 'https://cards.scryfall.io/normal/front/a/4/a45b534b-8442-4074-a8d2-f38e83f24868.jpg',
        similarityScore: 90,
        role: 'cheapest',
        whySimilar: '2-CMC green enchantment giving your entire creature suite mana tap abilities.',
        whatItDoesDifferently: 'Saga with two turns of mana tapping followed by a game-ending combat pump.',
        advantages: ['Costs under $0.50 (99% savings)', 'Chapter III provides an unblockable lethal wincon'],
        disadvantages: ['Sacrifices itself after Chapter III'],
        idealDeckSituation: 'Aggro and token swarm decks.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Mana Enablers & Ramp',
  },

  'coat-of-arms': {
    cardName: 'Coat of Arms',
    cleanSlug: 'coat-of-arms',
    marketPrice: 16.00,
    manaValue: 5,
    colorIdentity: [],
    typeLine: 'Artifact',
    oracleText: 'Each creature gets +1/+1 for each other creature on the battlefield that shares at least one creature type with it.',
    imageUri: 'https://cards.scryfall.io/normal/front/5/1/513d4c36-6ad4-4ee9-b161-3136eb59504f.jpg',
    cardRole: 'Universal Tribal Anthem & Finisher',
    summaryProblem: 'Coat of Arms turns small tribal armies into 10/10 behemoths overnight. However, at $16+ and with symmetrical math that can accidentally buff opponent tribal boards, players need cheaper, one-sided tribal anthems.',
    whyExpensive: 'Classic colorless anthem that fits into every tribal deck in Magic\'s history.',
    bestOverallReason: 'Shared Animosity & Vanquisher\'s Banner provide massive asymmetrical tribal buffs without helping opponents.',
    cheapestReason: 'Door of Destinies ($4.50) and Cathars\' Crusade ($2.50) scale tribal power exponentially.',
    closestFunctionalReason: 'Shared Animosity grants +1/+0 per attacking kindred creature for only 3 mana.',
    whenNotToSwap: 'In casual multiplayer pods where you want pure colorless anthem power regardless of color identity.',
    archetypeGuidance: [
      { archetype: 'Red Tribal (Goblins / Dragons)', recommendedCard: 'Shared Animosity', rationale: 'Only costs 3 mana ({2}{R}) and gives +1/+0 per attacker.' },
      { archetype: 'Card Draw + Tribal', recommendedCard: 'Vanquisher\'s Banner', rationale: 'Gives +1/+1 and draws a card on every tribal creature cast.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Coat of Arms?', answer: 'Shared Animosity ($1.50) and Vanquisher\'s Banner ($4.50) are the top alternatives.' },
    ],
    alternatives: [
      {
        name: 'Shared Animosity',
        manaValue: 3,
        typeLine: 'Enchantment',
        priceUsd: 1.50,
        oracleText: 'Whenever a creature you control attacks, it gets +1/+0 until end of turn for each other attacking creature that shares a creature type with it.',
        imageUri: 'https://cards.scryfall.io/normal/front/b/b/bb6a5635-508f-404b-99d7-8452796fe9e4.jpg',
        similarityScore: 93,
        role: 'best_overall',
        whySimilar: 'Tribal anthem scaling with the number of shared creature types.',
        whatItDoesDifferently: 'Only buffs YOUR creatures during attack, costs 3 mana ({2}{R}) instead of 5.',
        advantages: ['Completely asymmetrical (does not buff opponents)', 'Costs only 3 mana', 'Costs under $2.00 (90% savings)'],
        disadvantages: ['Requires Red mana', 'Only buffs power on attack'],
        idealDeckSituation: 'Go-wide tribal decks like Goblins, Elves, and Vampires.',
      },
    ],
    relatedHubSlug: 'staples',
    relatedCategoryName: 'Tribal Anthems & Buffs',
  },

  'displacer-kitten': {
    cardName: 'Displacer Kitten',
    cleanSlug: 'displacer-kitten',
    marketPrice: 14.00,
    manaValue: 4,
    colorIdentity: ['U'],
    typeLine: 'Creature — Cat',
    oracleText: 'Avoidance — Whenever you cast a noncreature spell, exile up to one target nonland permanent you control, then return that card to the battlefield under its owner\'s control.',
    imageUri: 'https://cards.scryfall.io/normal/front/c/7/c7a401b8-29fb-46ef-a663-427f67724a54.jpg',
    cardRole: 'Noncreature Spell-Triggered Blink & Infinite Mana Engine',
    summaryProblem: 'Displacer Kitten blinks Teferi, mana rocks, or ETB creatures whenever you cast a noncreature spell, creating instant-win loops with zero mana investment. At $14+, budget blink players need reliable flicker engines.',
    whyExpensive: 'cEDH and casual combo staple that blinks planeswalkers and mana rocks with no mana cost.',
    bestOverallReason: 'Teleportation Circle & Thassa, Deep-Dwelling provide free end-step blinks every turn cycle.',
    cheapestReason: 'Conjurer\'s Closet ($1.20) and Soulherder ($0.45) offer free turn-by-turn flickers.',
    closestFunctionalReason: 'Deadeye Navigator blinks any creature repeatedly for {1}{U}.',
    whenNotToSwap: 'When your combo specifically relies on blinking noncreature permanents (like Sol Ring or Teferi, Time Raveler) upon casting noncreature spells.',
    archetypeGuidance: [
      { archetype: 'Blink / ETB Value', recommendedCard: 'Teleportation Circle', rationale: 'Free end-step blink for artifacts and creatures on a 4-CMC enchantment.' },
      { archetype: 'Azorius Flicker', recommendedCard: 'Soulherder', rationale: 'Grows with +1/+1 counters and flickers creatures on your end step.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Displacer Kitten?', answer: 'Teleportation Circle ($4.50) and Soulherder ($0.45) are the best alternatives for repeatable blink value.' },
    ],
    alternatives: [
      {
        name: 'Soulherder',
        manaValue: 3,
        typeLine: 'Creature — Spirit',
        priceUsd: 0.45,
        oracleText: 'Whenever a creature is exiled from the battlefield, put a +1/+1 counter on Soulherder.\nAt the beginning of your end step, you may exile another target creature you control, then return that card to the battlefield under its owner\'s control.',
        imageUri: 'https://cards.scryfall.io/normal/front/5/0/504c55cc-753b-4f96-8c4c-73898236c535.jpg',
        similarityScore: 89,
        role: 'best_overall',
        whySimilar: 'Cheap creature providing repeatable blink triggers.',
        whatItDoesDifferently: 'Flickers at end step rather than on noncreature cast.',
        advantages: ['Costs only 3 mana ({1}{W}{U})', 'Costs under $0.50', 'Grows in power'],
        disadvantages: ['Only blinks creatures (not artifacts or planeswalkers)'],
        idealDeckSituation: 'Azorius or Esper blink decks.',
      },
    ],
    relatedHubSlug: 'protection',
    relatedCategoryName: 'Blink & Protection Spells',
  },

  'gaeas-cradle': {
    cardName: 'Gaea\'s Cradle',
    cleanSlug: 'gaeas-cradle',
    marketPrice: 850.00,
    manaValue: 0,
    colorIdentity: ['G'],
    typeLine: 'Legendary Land',
    oracleText: '{T}: Add {G} for each creature you control.',
    imageUri: 'https://cards.scryfall.io/normal/front/2/5/25b0b816-0583-44aa-9dc5-f3ff48993a51.jpg',
    cardRole: 'Creature-Scaling Big Mana Land',
    summaryProblem: 'Gaea\'s Cradle is the most powerful green land in Magic\'s history, tapping for 10–30+ green mana in token and swarm decks. At $850+ on the Reserved List, 99.9% of players need accessible budget substitutes.',
    whyExpensive: 'Reserved list rarity and unmatched mana generation on an untapped land slot.',
    bestOverallReason: 'Growing Rites of Itlimoc flips into Itlimoc, Cradle of the Sun—the literal functional clone of Gaea\'s Cradle—for under $5.',
    cheapestReason: 'Circle of Dreams Druid ($3.50) and Elvish Guidance ($1.20) tap for green mana equal to your creature/elf count.',
    closestFunctionalReason: 'Growing Rites of Itlimoc is a direct, printed 1:1 functional counterpart when flipped.',
    whenNotToSwap: 'In tournament Vintage/Legacy where playing an untapped land on turn 1 to generate 4 mana is required.',
    archetypeGuidance: [
      { archetype: 'Creature Swarm / Green', recommendedCard: 'Growing Rites of Itlimoc', rationale: 'Finds a creature on entry, then flips at end step into Itlimoc, Cradle of the Sun.' },
      { archetype: 'Elfball / Devotion', recommendedCard: 'Circle of Dreams Druid', rationale: '3-drop creature that taps for {G} for each creature you control.' },
      { archetype: 'Aura Ramp', recommendedCard: 'Elvish Guidance', rationale: 'Enchants a land to tap for {G} per Elf on the battlefield.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Gaea\'s Cradle in MTG?', answer: 'Growing Rites of Itlimoc ($4.80) is the best alternative. It searches for a creature on entry and transforms at end step into Itlimoc, Cradle of the Sun ({T}: Add {G} for each creature you control).' },
      { question: 'What is the cheapest card that acts like Gaea\'s Cradle?', answer: 'Circle of Dreams Druid ($3.50) and Karametra\'s Acolyte ($0.45) provide cradle-level mana on budget creature bodies.' },
    ],
    alternatives: [
      {
        name: 'Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun',
        manaValue: 3,
        typeLine: 'Legendary Enchantment // Legendary Land',
        priceUsd: 4.80,
        oracleText: 'When Growing Rites of Itlimoc enters the battlefield, look at the top four cards of your library. You may reveal a creature card from among them and put it into your hand.\nAt the beginning of your end step, if you control four or more creatures, transform Growing Rites of Itlimoc.\n//\nItlimoc, Cradle of the Sun: {T}: Add {G} for each creature you control.',
        imageUri: 'https://cards.scryfall.io/normal/front/0/0/004524bf-b249-4dac-9c10-44d57143feb9.jpg',
        similarityScore: 98,
        role: 'best_overall',
        whySimilar: 'Transforms into Itlimoc, Cradle of the Sun, which has the EXACT oracle text as Gaea\'s Cradle.',
        whatItDoesDifferently: 'Starts as a 3-mana enchantment that replaces itself with a creature before transforming.',
        advantages: ['Draws a creature on entry', 'Literally becomes Gaea\'s Cradle on turn 3', 'Costs under $5.00 (99.4% savings)'],
        disadvantages: ['Requires 4 creatures to flip at end step'],
        idealDeckSituation: 'Any green creature, elf, or token deck.',
      },
      {
        name: 'Circle of Dreams Druid',
        manaValue: 3,
        typeLine: 'Creature — Elf Druid',
        priceUsd: 3.50,
        oracleText: '{T}: Add {G} for each creature you control.',
        imageUri: 'https://cards.scryfall.io/normal/front/3/4/3409663b-3115-460c-9738-b87d818aea03.jpg',
        similarityScore: 96,
        role: 'closest_functional',
        whySimilar: 'Shares the EXACT oracle text: "{T}: Add {G} for each creature you control."',
        whatItDoesDifferently: 'Printed on a 3-mana creature body ({G}{G}{G}) rather than a land.',
        advantages: ['Taps for massive mana immediately if given haste', 'Counts itself as 1 creature'],
        disadvantages: ['Vulnerable to creature removal and summoning sickness'],
        idealDeckSituation: 'Elf tribal and mono-green stompy decks.',
      },
    ],
    relatedHubSlug: 'ramp',
    relatedCategoryName: 'Green Big Mana & Lands',
  },

  'demonic-tutor': {
    cardName: 'Demonic Tutor',
    cleanSlug: 'demonic-tutor',
    marketPrice: 42.00,
    manaValue: 2,
    colorIdentity: ['B'],
    typeLine: 'Sorcery',
    oracleText: 'Search your library for a card, put that card into your hand, then shuffle.',
    imageUri: 'https://cards.scryfall.io/normal/front/b/2/b250d531-da58-4405-8d02-1a2389020305.jpg',
    cardRole: 'Unconditional 2-Mana Universal Tutor',
    summaryProblem: 'Demonic Tutor is Magic’s cleanest search card: 2 mana to find ANY card in your deck and put it directly into your hand. At $42+, budget Black deck builders need accessible search spells and transmute options.',
    whyExpensive: 'The definitive tutor across Commander, Vintage, and Cube with zero restrictions or drawbacks.',
    bestOverallReason: 'Diabolic Intent costs 2 mana and requires sacrificing a creature—an upside in Black Aristocrat decks.',
    cheapestReason: 'Profane Tutor ($1.90), Beseech the Queen ($2.00), and Wishclaw Talisman ($2.80) tutor for pennies.',
    closestFunctionalReason: 'Diabolic Intent & Profane Tutor search for any card with zero type restrictions.',
    whenNotToSwap: 'In hyper-competitive cEDH lists where casting an unconditional tutor with zero board state on turn 2 is mandatory.',
    archetypeGuidance: [
      { archetype: 'Aristocrats / Tokens', recommendedCard: 'Diabolic Intent', rationale: 'Sacrifices a 1/1 token or Bloodghast to search any card for only {1}{B}.' },
      { archetype: 'Midrange / Control', recommendedCard: 'Wishclaw Talisman', rationale: 'Searches for a combo piece on command for {1}{B}.' },
      { archetype: 'Slow / Cascade', recommendedCard: 'Profane Tutor', rationale: 'Suspend 2 tutor that costs only {1}{B} with zero extra mana investment.' },
    ],
    customFaqs: [
      { question: 'What is the best alternative to Demonic Tutor in MTG?', answer: 'Diabolic Intent ($4.50) is the closest functional equivalent, searching for any card for {1}{B} and a creature sacrifice.' },
      { question: 'What are the best cheap Black tutors under $3?', answer: 'Profane Tutor ($1.90), Wishclaw Talisman ($2.80), Beseech the Queen ($2.00), and Diabolic Tutor ($0.75).' },
    ],
    alternatives: [
      {
        name: 'Diabolic Intent',
        manaValue: 2,
        typeLine: 'Sorcery',
        priceUsd: 4.50,
        oracleText: 'As an additional cost to cast this spell, sacrifice a creature.\nSearch your library for a card, put that card into your hand, then shuffle.',
        imageUri: 'https://cards.scryfall.io/normal/front/d/7/d72ab6d6-1677-4fb5-a50e-13c4779229fb.jpg',
        similarityScore: 97,
        role: 'best_overall',
        whySimilar: '2-CMC black sorcery that searches your library for ANY card directly into hand.',
        whatItDoesDifferently: 'Requires sacrificing a creature as an additional casting cost.',
        advantages: ['Shares the exact same 2-mana cost ({1}{B})', 'Searches for ANY card', 'Costs under $5.00 (89% savings)'],
        disadvantages: ['Requires a creature on the battlefield to cast'],
        idealDeckSituation: 'Aristocrats, reanimation, and token decks.',
      },
      {
        name: 'Profane Tutor',
        manaValue: 0,
        typeLine: 'Sorcery',
        priceUsd: 1.90,
        oracleText: 'Suspend 2—{1}{B}\nSearch your library for a card, put that card into your hand, then shuffle.',
        imageUri: 'https://cards.scryfall.io/normal/front/f/b/fb6b0541-045a-450c-9797-05669b2e059a.jpg',
        similarityScore: 93,
        role: 'cheapest',
        whySimilar: 'Searches for ANY card directly into your hand for {1}{B}.',
        whatItDoesDifferently: 'Uses Suspend 2, resolving 2 turns after casting.',
        advantages: ['Costs only {1}{B} to suspend', 'No creature sacrifice required', 'Costs under $2.00 (95% savings)'],
        disadvantages: ['Delayed by 2 turns'],
        idealDeckSituation: 'Midrange, control, and casual Commander lists.',
      },
    ],
    relatedHubSlug: 'tutors',
    relatedCategoryName: 'Black Tutors & Search Spells',
  },
};

export function getCuratedGuide(slug: string): CuratedCardGuide | null {
  const clean = slug
    .replace(/^budget-options-for-/, '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9-]/gi, '')
    .toLowerCase();

  return CURATED_CARD_GUIDES[clean] || null;
}
